function [ApoI, IntKapoi] = getApoI(p)
% GETAPOI calculates the infection time-dependent apoptosis rates and 
%   calculates the integral of kApoT+kApoI(tau)
%
%   last revised: 2018/11/21

switch lower(p.Apo.Increase)
    case{'none'}
        ApoI     =      (p.Ex.kApoT + p.Ex.kApoI)*ones(size(p.Ex.tspan));
        IntKapoi = exp(-(p.Ex.kApoT + p.Ex.kApoI)*p.Ex.tspan);

    case{'linear'}
        ApoI     =      p.Ex.kApoT + p.Ex.kApoI.*p.Ex.tspan;
        IntKapoi = exp(- ( (p.Ex.tspan.*p.Ex.kApoT) + (0.5.*p.Ex.kApoI.*p.Ex.tspan.^2) ) );

    case{'hill1','hill2','hill3','hill4'} % p.Ex.v_Apo = n // p.Ex.tau_Apo = K_h = H
        p.Ex.v_Apo = str2double(p.Apo.Increase(end));

        ApoI_tau = p.Ex.kApoI .* p.Ex.tspan.^p.Ex.v_Apo ./(p.Ex.tau_Apo^p.Ex.v_Apo + p.Ex.tspan.^p.Ex.v_Apo);
        ApoI     = p.Ex.kApoT + ApoI_tau;

        % varying hill coefficients (integer) generate different integral solutions
        if (strcmp(p.Apo.Increase(end),'1'))
            IntKapoi = exp(-( ...
                p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI.*( ...
                    p.Ex.tspan + p.Ex.tau_Apo.*log(p.Ex.tau_Apo./(p.Ex.tau_Apo+p.Ex.tspan)) ...
                ) ...
            ) );                     

        elseif (strcmp(p.Apo.Increase(end),'2'))
            IntKapoi = exp(-( ...
                p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI.*( ...
                    p.Ex.tspan - p.Ex.tau_Apo.*atan(p.Ex.tspan./p.Ex.tau_Apo) ...
                ) ...
            ) );

        elseif (strcmp(p.Apo.Increase(end),'3'))                                                                
            IntKapoi = exp(-( ...
                p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI./6.*( ...
                    6.*p.Ex.tspan + p.Ex.tau_Apo.*( ...
                        log(abs(p.Ex.tspan.^2 - p.Ex.tau_Apo.*p.Ex.tspan + p.Ex.tau_Apo.^2)./(p.Ex.tau_Apo+p.Ex.tspan).^2) ...
                        + 2.*sqrt(3).*(atan(-1./sqrt(3)) - atan((2.*p.Ex.tspan-p.Ex.tau_Apo)./(sqrt(3).*p.Ex.tau_Apo))) ...
                    ) ...
                ) ...
            ) );                                         

        elseif (strcmp(p.Apo.Increase(end),'4'))                                                                                              
            IntKapoi = exp(-( ...
                p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI.*p.Ex.tspan - 2^(-2.5).*p.Ex.tau_Apo.*p.Ex.kApoI.*( ...
                    log((p.Ex.tspan.^2+sqrt(2).*p.Ex.tau_Apo.*p.Ex.tspan+p.Ex.tau_Apo.^2)./(abs(p.Ex.tspan.^2-sqrt(2).*p.Ex.tau_Apo.*p.Ex.tspan+p.Ex.tau_Apo.^2))) ...
                    + 2.*(atan((sqrt(2).*p.Ex.tspan+p.Ex.tau_Apo)./p.Ex.tau_Apo) + atan((sqrt(2).*p.Ex.tspan-p.Ex.tau_Apo)./p.Ex.tau_Apo)) ...
                ) ...
            ) );                      
        end
        
    case{'gompertz'} % p.Ex.v_Apo = c // p.Ex.tau_Apo = b
        ApoI_tau = p.Ex.kApoI.*exp(-p.Ex.v_Apo.*exp(-p.Ex.tau_Apo.*p.Ex.tspan));
        ApoI     = p.Ex.kApoT + ApoI_tau;
        
        IntKapoi = exp(-( ...
            p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI./p.Ex.tau_Apo.*( ...
                expint(p.Ex.v_Apo*exp(-p.Ex.tau_Apo.*p.Ex.tspan)) - expint(p.Ex.v_Apo) ...
            ) ...
        ) );
    
    case{'logistic'}                  
        ApoI_tau = p.Ex.kApoI./(1+exp(- p.Ex.v_Apo*(p.Ex.tspan - p.Ex.tau_Apo) ) );
        ApoI     = p.Ex.kApoT + ApoI_tau;

        IntKapoi = exp(-( ...
            p.Ex.tspan.*p.Ex.kApoT + p.Ex.kApoI/p.Ex.v_Apo.*( ...
                log( (exp(-p.Ex.v_Apo*(p.Ex.tspan-p.Ex.tau_Apo))+1) ./ (exp(p.Ex.v_Apo*p.Ex.tau_Apo)+1) ) ...
                    + p.Ex.v_Apo*p.Ex.tspan ...
            ) ...
        ) ); 

    case{'normal_distribution'}       
        ApoI_tau = p.Ex.kApoI .* 0.5 .* (1 + erf((p.Ex.tspan-p.Ex.tau_Apo)./p.Ex.v_Apo./sqrt(2)));
        ApoI     = p.Ex.kApoT + ApoI_tau;
        
        IntKapoi = exp(-(...
            p.Ex.tspan.*p.Ex.kApoT + 0.5.*p.Ex.kApoI.*...
              ( p.Ex.tspan ...
                + ( (p.Ex.tspan-p.Ex.tau_Apo).*erf((p.Ex.tspan-p.Ex.tau_Apo)./p.Ex.v_Apo./sqrt(2))...
                    + p.Ex.v_Apo.*sqrt(2)./sqrt(pi).*exp(-((p.Ex.tspan-p.Ex.tau_Apo).^2)./2./p.Ex.v_Apo.^2)...
                  ) ...
                - ( -p.Ex.tau_Apo.*erf((-p.Ex.tau_Apo)./p.Ex.v_Apo./sqrt(2))...
                                + p.Ex.v_Apo.*sqrt(2)./sqrt(pi).*exp(-(p.Ex.tau_Apo.^2)./2./p.Ex.v_Apo.^2)...
                  ) ...
              ) ...
        ) );

    otherwise
        error('Error: Apoptosis rate increase must be defined correctly!');
end 

